PROGRAM = game.prg

CC = cc68x
AS = gen

CFLAGS = -c -g
LDFLAGS = -g
ASFLAGS = -L2 -D

OBJS = rMain.o vbl.o

$(PROGRAM): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $(PROGRAM)

rMain.o: rMain.c vbl.h
	$(CC) $(CFLAGS) rMain.c

vbl.o: vbl.s
	$(AS) $(ASFLAGS) vbl.s

clean:
	rm -f *.o $(PROGRAM)